name: BTC Daily Alerts

on:
  schedule:
    - cron: "22 5,10,15 * * *"  # เวลาไทย 12:22, 17:22, 22:22 (UTC)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance requests pytz

      - name: Run BTC script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID_BTC: ${{ secrets.CHAT_ID_BTC }}
          FORCE_RUN: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
        run: python btc_notify.py
